# Generated by Django 5.0.6 on 2024-06-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prodpics')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
