# Generated by Django 5.0.6 on 2024-06-15 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_bottles'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='medium',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
