# Generated by Django 5.0.6 on 2024-06-17 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_products_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottles',
            name='medium',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
