# Generated by Django 5.0.6 on 2024-06-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Canvas',
        ),
    ]
