# Generated by Django 5.0.6 on 2024-06-24 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='testimonialpics'),
            preserve_default=False,
        ),
    ]
