# Generated by Django 5.0.6 on 2024-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_testimonials_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='otherImages')),
            ],
        ),
    ]
