# Generated by Django 5.0.6 on 2024-07-15 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='size',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
