# Generated by Django 5.0.6 on 2024-07-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_canvas_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
