# Generated by Django 5.0.6 on 2024-07-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_order_address_order_email_order_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
