# Generated by Django 5.0.6 on 2024-07-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
