# Generated by Django 5.0.6 on 2024-07-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
