# Generated by Django 5.0.6 on 2024-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_bottles_description_alter_canvas_description_and_more'),
        ('Home', '0026_remove_order_phone'),
    ]

    operations = [
    ]
