# Generated by Django 5.0.6 on 2024-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_merge_20240718_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='254', max_length=30),
        ),
    ]
